// <auto-generated />
namespace RelayTest.Properties {
    using System;
    using System.Configuration;

    internal sealed partial class Settings : ApplicationSettingsBase {
        private static readonly Settings defaultInstance =
            (Settings)Synchronized(new Settings());

        public static Settings Default => defaultInstance;

        [UserScopedSetting]
        [DefaultSettingValue("")]
        public string JournalPath {
            get => (string)this[nameof(JournalPath)] ?? string.Empty;
            set => this[nameof(JournalPath)] = value;
        }

        [UserScopedSetting]
        [DefaultSettingValue("")]
        public string RelayAddress {
            get => (string)this[nameof(RelayAddress)] ?? string.Empty;
            set => this[nameof(RelayAddress)] = value;
        }
    }
}